on:
  push:
    branches: 
      - master
name: Build and deploy on push
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy
      uses: ./.github/actions/deploy
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
